import {InMemoryDbService} from 'angular-in-memory-web-api';

export class InMemoryDb implements InMemoryDbService {
  createDb() {
    const produces = [
      {id: 1, name: 'Product1', category: 'Category1', description: 'description1', price: 11},
      {id: 2, name: 'Product2', category: 'Category2', description: 'description2', price: 22},
      {id: 3, name: 'Product3', category: 'Category3', description: 'description3', price: 33},
      {id: 4, name: 'Product4', category: 'Category4', description: 'description4', price: 44},
      {id: 5, name: 'Product5', category: 'Category5', description: 'description5', price: 55},
      {id: 6, name: 'Product6', category: 'Category6', description: 'description6', price: 66},
      {id: 7, name: 'Product7', category: 'Category7', description: 'description7', price: 77},
      {id: 8, name: 'Product8', category: 'Category8', description: 'description8', price: 88},
      {id: 9, name: 'Product9', category: 'Category9', description: 'description9', price: 99},
      {id: 10, name: 'Product10', category: 'Category10', description: 'description10', price: 100},
      {id: 11, name: 'Product11', category: 'Category11', description: 'description11', price: 110},
      {id: 12, name: 'Product12', category: 'Category12', description: 'description12', price: 120},
      {id: 13, name: 'Product13', category: 'Category13', description: 'description13', price: 130},
      {id: 14, name: 'Product14', category: 'Category14', description: 'description14', price: 140},
      {id: 15, name: 'Product15', category: 'Category15', description: 'description15', price: 150},
      {id: 16, name: 'Product16', category: 'Category16', description: 'description16', price: 160},
      {id: 17, name: 'Product17', category: 'Category17', description: 'description17', price: 170},
      {id: 18, name: 'Product18', category: 'Category18', description: 'description18', price: 180},
    ];
    const heroes = [
      {id: 11, name: 'Mr. Nice'},
      {id: 12, name: 'Narco'},
      {id: 13, name: 'Bombasto'},
      {id: 14, name: 'Celeritas'},
      {id: 15, name: 'Magneta'},
      {id: 16, name: 'RubberMan'},
      {id: 17, name: 'Dynama'},
      {id: 18, name: 'Dr IQ'},
      {id: 19, name: 'Magma'},
      {id: 20, name: 'Tornado'}
    ];
    return {produces, heroes};
  }
}

export const china = [
  {
    'id': 100,
    'name': '北京市',
    'cityList': [
      {'id': 10000, 'name': '东城区', 'areaList': ''},
      {'id': 10001, 'name': '西城区', 'areaList': ''},
      {'id': 10002, 'name': '崇文区', 'areaList': ''},
      {'id': 10003, 'name': '宣武区', 'areaList': ''},
      {'id': 10004, 'name': '朝阳区', 'areaList': ''},
      {'id': 10005, 'name': '海淀区', 'areaList': ''},
      {'id': 10006, 'name': '丰台区', 'areaList': ''},
      {'id': 10007, 'name': '石景山区', 'areaList': ''},
      {'id': 10008, 'name': '房山区', 'areaList': ''},
      {'id': 10009, 'name': '通州区', 'areaList': ''},
      {'id': 10010, 'name': '顺义区', 'areaList': ''},
      {'id': 10011, 'name': '大兴区', 'areaList': ''},
      {'id': 10012, 'name': '昌平区', 'areaList': ''},
      {'id': 10013, 'name': '平谷区', 'areaList': ''},
      {'id': 10014, 'name': '怀柔区', 'areaList': ''},
      {'id': 10015, 'name': '门头沟区', 'areaList': ''},
      {'id': 10016, 'name': '密云县', 'areaList': ''},
      {'id': 10017, 'name': '延庆县', 'areaList': ''},
    ]
  },
  {
    'id': 101,
    'name': '天津市',
    'cityList': [
      {'id': 10100, 'name': '和平区', 'areaList': ''},
      {'id': 10101, 'name': '河东区', 'areaList': ''},
      {'id': 10102, 'name': '河西区', 'areaList': ''},
      {'id': 10103, 'name': '南开区', 'areaList': ''},
      {'id': 10104, 'name': '河北区', 'areaList': ''},
      {'id': 10105, 'name': '红桥区', 'areaList': ''},
      {'id': 10106, 'name': '塘沽区', 'areaList': ''},
      {'id': 10107, 'name': '汉沽区', 'areaList': ''},
      {'id': 10108, 'name': '大港区', 'areaList': ''},
      {'id': 10109, 'name': '东丽区', 'areaList': ''},
      {'id': 10110, 'name': '西青区', 'areaList': ''},
      {'id': 10111, 'name': '津南区', 'areaList': ''},
      {'id': 10112, 'name': '北辰区', 'areaList': ''},
      {'id': 10113, 'name': '武清区', 'areaList': ''},
      {'id': 10114, 'name': '宝坻区', 'areaList': ''},
      {'id': 10115, 'name': '蓟县', 'areaList': ''},
      {'id': 10116, 'name': '宁河县', 'areaList': ''},
      {'id': 10117, 'name': '静海县', 'areaList': ''},
    ]
  },
  {
    'id': 102, 'name': '上海市', 'cityList': [
      {'id': 10200, 'name': '宝山', 'areaList': ''},
      {'id': 10201, 'name': '崇明', 'areaList': ''},
      {'id': 10202, 'name': '嘉定', 'areaList': ''},
      {'id': 10203, 'name': '青浦', 'areaList': ''},
      {'id': 10204, 'name': '松江', 'areaList': ''},
      {'id': 10205, 'name': '金山', 'areaList': ''},
      {'id': 10206, 'name': '奉贤', 'areaList': ''},
      {'id': 10207, 'name': '闵行', 'areaList': ''},
      {'id': 10208, 'name': '浦东新区', 'areaList': ''},
      {'id': 10209, 'name': '普陀', 'areaList': ''},
      {'id': 10210, 'name': '长宁', 'areaList': ''},
      {'id': 10211, 'name': '徐汇', 'areaList': ''},
      {'id': 10212, 'name': '卢湾', 'areaList': ''},
      {'id': 10213, 'name': '静安', 'areaList': ''},
      {'id': 10214, 'name': '闸北', 'areaList': ''},
      {'id': 10215, 'name': '虹口', 'areaList': ''},
      {'id': 10216, 'name': '黄浦', 'areaList': ''},
      {'id': 10217, 'name': '杨浦', 'areaList': ''},
    ]
  },
  {
    'id': 103, 'name': '重庆市', 'cityList': [
      {'id': 10300, 'name': '万州区', 'areaList': ''},
      {'id': 10300, 'name': '涪陵区', 'areaList': ''},
      {'id': 10300, 'name': '渝中区', 'areaList': ''},
      {'id': 10300, 'name': '大渡口区', 'areaList': ''},
    ]
  },
  {
    'id': 104, 'name': '河北省', 'cityList': [
      {
        'id': 10400, 'name': '承德市', 'areaList': [
          {'id': 1040000, 'name': '围场满族蒙古族自治县'},
          {'id': 1040001, 'name': '丰宁满族自治县'},
          {'id': 1040001, 'name': '隆化县'},
          {'id': 1040001, 'name': '滦平县'},
          {'id': 1040001, 'name': '平泉县'},
          {'id': 1040001, 'name': '承德县'},
          {'id': 1040001, 'name': '宽城满族自治县'},
          {'id': 1040001, 'name': '兴隆县'},
          {'id': 1040001, 'name': '双桥区'},
          {'id': 1040001, 'name': '双滦区'},
          {'id': 1040001, 'name': '鹰手营子矿区'},
        ]
      },
      // {'id': 10401, 'name': '张家口市', 'areaList': ''},
      // {'id': 10402, 'name': '保定市', 'areaList': ''},
      // {'id': 10403, 'name': '石家庄市', 'areaList': ''},
      // {'id': 10404, 'name': '邢台市', 'areaList': ''},
      // {'id': 10405, 'name': '邯郸市', 'areaList': ''},
      // {'id': 10406, 'name': '衡水市', 'areaList': ''},
      // {'id': 10407, 'name': '沧州市', 'areaList': ''},
      // {'id': 10408, 'name': '廊坊市', 'areaList': ''},
      // {'id': 10409, 'name': '唐山市', 'areaList': ''},
      // {'id': 104010, 'name': '秦皇岛市', 'areaList': ''},
    ]
  },
  // {'id': 105, 'name': '山西省', 'cityList': ''},
  // {'id': 106, 'name': '陕西省', 'cityList': ''},
  // {'id': 107, 'name': '山东省', 'cityList': ''},
  // {'id': 108, 'name': '河南省', 'cityList': ''},
  // {'id': 109, 'name': '辽宁省', 'cityList': ''},
  // {'id': 110, 'name': '吉林省', 'cityList': ''},
  // {'id': 111, 'name': '黑龙江省', 'cityList': ''},
  // {'id': 112, 'name': '江苏省', 'cityList': ''},
  // {'id': 113, 'name': '浙江省', 'cityList': ''},
  // {'id': 114, 'name': '安徽省', 'cityList': ''},
  // {'id': 115, 'name': '江西省', 'cityList': ''},
  // {'id': 116, 'name': '福建省', 'cityList': ''},
  // {'id': 117, 'name': '湖北省', 'cityList': ''},
  // {'id': 118, 'name': '湖南省', 'cityList': ''},
  // {'id': 119, 'name': '四川省', 'cityList': ''},
  // {'id': 120, 'name': '贵州省', 'cityList': ''},
  // {'id': 121, 'name': '云南省', 'cityList': ''},
  // {'id': 122, 'name': '广东省', 'cityList': ''},
  // {'id': 123, 'name': '海南省', 'cityList': ''},
  // {'id': 124, 'name': '甘肃省', 'cityList': ''},
  // {'id': 125, 'name': '青海省', 'cityList': ''},
  // {'id': 126, 'name': '内蒙古自治区', 'cityList': ''},
  // {'id': 127, 'name': '新疆维吾尔自治区', 'cityList': ''},
  // {'id': 128, 'name': '西藏自治区', 'cityList': ''},
  // {'id': 129, 'name': '广西壮族自治区', 'cityList': ''},
  // {'id': 130, 'name': '宁夏回族自治区', 'cityList': ''},
];
